use_frameworks!

platform :ios, '8.0'

target 'YJProtocols_Example' do
  pod 'YJProtocols', :path => '../'

  target 'YJProtocols_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
